version: '3.8'
services:
  backend_sample_app:
    image: backend_sample_app:latest
    container_name: backend_sample_app
    build:
      context: .
      dockerfile: Dockerfile.local
    restart: always
    ports:
      - 4000:3000
    env_file: ./src/configs/.env.development
    environment:
      - DOCKER_ENV=true

    volumes:
      - ./src:/app/src         # Hot reloading for code changes
      - app_data:/app/data      # Named volume to persist data
    command: "nodemon ts-node /app/src/server.ts"

volumes:
  app_data:                     # This is the named volume, which will persist data